# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  modules-download-mode: readonly
output:
  print-issued-lines: false

linters:
  enable:
    - gofumpt
    - gci
    - gocritic
    - revive
    - gosec
